### ISSUE TITLE
ionic cordova build android 진행시 문의

### ISSUE THREAD

**Issue by pakusky10** [GwonHyeok/ionic-plugin-naver#6]
plugin 설치시 오류가 나서 문의 드립니다.

3rdparty_login_library_android_4.1.4.jar가 존재하는 것은 확인했는데
android 프로젝트에서 인식을 못하는 것 같습니다.
cordova와 ionic plugin을 추가하면, 추가된 libs가 인식되나요?
어떻게 하면 인식할 수 있게 할 수 있나요?

**Comment by pakusky10** [comment]
cordova-plugin-naver 이슈에 있는 아래 링크를 보고
https://github.com/GwonHyeok/cordova-plugin-naver/issues/4
안드로이드 스튜디오에서의 빌드 과정은 해결했는데,

ionic cordova build android 진행하면 여전히 아래와 같은 에러가 있습니다.

Unhandled "error" event. (Parsing H:\Ionic\xxxxx\platforms\android\res\xml\config.xml failed)
Error: Unhandled "error" event. (Parsing H:\Ionic\xxxxx\platforms\android\res\xml\config.xml failed)
    at EventEmitter.emit (events.js:186:19)
    at EventEmitter.module.exports.emit (C:\Users\zzz\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-common\src\events.js:71:17)
    at EventEmitter.module.exports.emit (H:\Ionic\xxxxx\platforms\android\cordova\node_modules\cordova-common\src\events.js:68:30)
    at new ConfigParser (H:\Ionic\xxxxx\platforms\android\cordova\node_modules\cordova-common\src\ConfigParser\ConfigParser.js:34:16)
    at updateConfigFilesFrom (H:\Ionic\xxxxx\platforms\android\cordova\lib\prepare.js:106:18)
    at Api.module.exports.prepare (H:\Ionic\xxxxx\platforms\android\cordova\lib\prepare.js:42:20)
    at Api.prepare (H:\Ionic\xxxxx\platforms\android\cordova\Api.js:192:45)
    at C:\Users\zzz\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\cordova\prepare.js:105:36
    at _fulfilled (C:\Users\zzz\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:854:54)
    at self.promiseDispatch.done (C:\Users\zzz\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:883:30)
[ERROR] An error occurred while running subprocess cordova.

        cordova build android --verbose exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.
